name: solaiman.me/cardgameapi

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          go get .
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Static Check
        run: staticcheck

      - name: Test
        run: go test